// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiFinalGomezFederico.Models;

namespace WebApiFinalGomezFederico.Migrations
{
    [DbContext(typeof(DbhospitalApiContext))]
    [Migration("20221118193325_altertable3")]
    partial class altertable3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiFinalGomezFederico.Models.Doctor", b =>
                {
                    b.Property<int>("Doctor_NO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Especialidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hospital_Cod")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Doctor_NO");

                    b.HasIndex("Hospital_Cod");

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("WebApiFinalGomezFederico.Models.Hospital", b =>
                {
                    b.Property<int>("Hospital_Cod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Num_Cama")
                        .HasColumnType("int");

                    b.Property<int>("numeroTelefono")
                        .HasColumnType("int");

                    b.HasKey("Hospital_Cod");

                    b.ToTable("hospital");
                });

            modelBuilder.Entity("WebApiFinalGomezFederico.Models.Doctor", b =>
                {
                    b.HasOne("WebApiFinalGomezFederico.Models.Hospital", "Hospital")
                        .WithMany("Doctores")
                        .HasForeignKey("Hospital_Cod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
